name: Trigger S3 Upload

on:
  push:
    branches:
      - dev-build-test
  workflow_dispatch:    

jobs:
  call-reusable:
    uses: UnityGames-UPS/unity-build-pipeline/.github/workflows/dev-test.yaml@main
    with:
      s3_bucket: unity.build-dev-test
      s3_folder: SL-RB
      cloudfront_distribution_id: E2PZXPTWLYYS3A
      invalidate_paths: "/SL-RB/*"
      
